image: python:3.10

include:
  - template: Python.gitlab-ci.yml



stages:
  - validate
  - build
  - test
  - deploy

before_script:
  - pip3 install -r requirements-dev.txt

validate:
  stage: validate
  script:
    - pre-commit run -a


test:
  stage: test
  script:
    - python3 setup.py build
    - python3 setup.py install
